# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Longevity Research
email: timothy.roy@protonmail.ch
description: Overview and Ways to Contribute
baseurl: "/longevity" # the subpath of your site, e.g. /blog
url: "coyotespike.github.io" # the base hostname & protocol for your site
twitter_username: coyotespike 
github_username:  coyotespike
paginate: 5
theme-dark: false
future: true

plugins: [jekyll-paginate, kramdown]
# Build settings
markdown: kramdown
